### ISSUE TITLE
结果集全选发起任务批量扫描时出现panic

### ISSUE THREAD

**Issue by skye96** [opensec-cn/kunpeng#36]

**Comment by skye96** [comment]
![微信图片_20190530082521](https://user-images.githubusercontent.com/48672012/58600028-5186f000-82b5-11e9-98f7-bd1a0157e92b.png)

**Comment by Medicean** [comment]
@skye96 能把详细的  debug log 打出来吗

**Comment by skye96** [comment]
windows版的debug log在哪看呢



18850592425@163.com
 
发件人： Medicean
发送时间： 2019-05-30 11:18
收件人： opensec-cn/kunpeng
抄送： skye96; Mention
主题： Re: [opensec-cn/kunpeng] 结果集全选发起任务批量扫描时出现panic (#36)
@skye96 能把详细的 debug log 打出来吗
―

**Comment by Medicean** [comment]
```
kunpeng.ShowLog()
```
参考：

https://github.com/opensec-cn/kunpeng/blob/master/example/call_so_test.py#L44

**Comment by ywolf** [comment]
这个我晚点测试一下是否影响扫描结果 如果只是单个目标panic 那可以不处理

**Comment by thinks520** [comment]
l类似的问题，求指导
panic: runtime error: index out of range

goroutine 645 [running]:
net/http.(*Transport).dialConn(0xc4204e20f0, 0x7fb5e8dbbcc0, 0xc4200140d8, 0xc420130080, 0x7fb5e83c179c, 0x5, 0xc420608780, 0x11, 0xc42065b280, 0x13, ...)
        /usr/local/go/src/net/http/transport.go:1128 +0x2092
net/http.(*Transport).getConn.func4(0xc4204e20f0, 0x7fb5e8dbbcc0, 0xc4200140d8, 0xc420388ae0, 0xc4206660c0)
        /usr/local/go/src/net/http/transport.go:943 +0x7a
created by net/http.(*Transport).getConn
        /usr/local/go/src/net/http/transport.go:942 +0x395
Aborted (core dumped)
